### ISSUE TITLE
Tracking issue: making `jspecify/jdk` library models available to NullAway users

### ISSUE THREAD

**Issue by msridhar** [uber/NullAway#950]
This issue is for tracking remaining changes we need to make to use the [jspecify/jdk](https://github.com/jspecify/jdk) library models with NullAway.  We added some initial support for parsing source code and generating `astubx` files in #922, with support only for reading in `@Nullable` return types.  (List below is quite incomplete for the moment)

- [X] #949
- [x] #1072 
- [ ] #940
- [ ] properly handle defaults for modeled `@NullMarked` classes (unannotated types are `@NonNull`) #1006 
- [ ] scripts to generate an `astubx` jar artifact that can be shipped to Maven Central
- [ ] add a flag for using the new models separate from JSpecify mode?
- [ ] #1493

**Comment by msridhar** [comment]
This is now fixed on the master branch, underneath a flag that is off by default (since it causes a bunch of new warnings in typical projects).  There are potentially more minor issues to fix (like #1498) but for the most part this is done.  So I'm going to close this issue!  Please file follow-ups where things don't work.
